### ISSUE TITLE
Chapter 01 Not defined error

### ISSUE THREAD

**Issue by bhatz829-zz** [PacktPublishing/Python-for-Finance-Cookbook#14]
df = df_all_dates.join(df[['adj_close']], how='left') \
                 .fillna(method='ffill') \
                 .asfreq('M')
                 
This is the line with the error. It says df is not defined.

**Comment by erykml** [comment]
Hi! You also need to run the code from the `How to do it...` section, it will execute without errors then :)

**Comment by shruthis-shetty** [comment]
Hi @bhatz829 , I hope the solution given by @erykml is useful. Let us know the updates.
