### ISSUE TITLE
'unzip' and 'rm' are not recognized commands

### ISSUE THREAD

**Issue by CarterFitz** [PacktPublishing/Python-for-Finance-Cookbook#4]
In using the code for chapter 4 cell #15 the shell commands '!unzip' and '!rm' give an error "not recognized as an internal or external command".  Do you know of a solution.  I am not that familiar with shell commands.

# download the zip file from Prof. French's website
!wget http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_CSV.zip

# unpack the zip
!unzip -a F-F_Research_Data_Factors_CSV.zip

# remove the zip
!rm F-F_Research_Data_Factors_CSV.zip
--2020-05-04 17:21:39--  http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_CSV.zip
Resolving mba.tuck.dartmouth.edu... 129.170.171.144
Connecting to mba.tuck.dartmouth.edu|129.170.171.144|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12389 (12K) [application/x-zip-compressed]
Saving to: `F-F_Research_Data_Factors_CSV.zip.7'

     0K .......... ..                                         100% 34.4M=0s

2020-05-04 17:21:39 (34.4 MB/s) - `F-F_Research_Data_Factors_CSV.zip.7' saved [12389/12389]

'unzip' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.

**Comment by erykml** [comment]
Hi Carter, 

I am guessing you are running this code on a Windows machine. If so, try installing the following (https://gitforwindows.org/) as the commands such as `unzip` and `rm` are native to macOS and Linux. 

Hope this helps!

P.S. You can always run the Notebooks on Google Colab. Then, you will have no issues with these commands :)
