### ISSUE TITLE
issue generating images/ch6_im2.png (Geometric Brownian Motion)

### ISSUE THREAD

**Issue by nickdesaulniers** [PacktPublishing/Python-for-Finance-Cookbook#6]
cc @erykml 

I was following along with the code in chapt. 6, but the plot of the simulations seemed off; maybe I had a typo I couldn't spot.

I downloaded the jupyter notebook for chpt 6 and reran it and got similar results.

![Screenshot from 2020-07-24 21-10-21](https://user-images.githubusercontent.com/1823839/88448375-28e38300-cdf2-11ea-8486-9f996b8e0993.png)

were my results.  This pretty much matches what I get from the python notebook.

(Also, I recommended this book to our local library, and I see on their website it's on order (though I already have my hardcopy) :sunglasses: )

**Comment by nickdesaulniers** [comment]
```diff
-ax = gbm_simulations_df.plot(alpha=0.2, legend=False)
+fig, ax = plt.subplots(1)
+ax.plot(gbm_simulations_df, alpha=0.2)
```
seems to work.
![Screenshot from 2020-07-24 21-26-50](https://user-images.githubusercontent.com/1823839/88448612-677a3d00-cdf4-11ea-8d73-75b28e4ecce1.png)

**Comment by erykml** [comment]
Hi @nickdesaulniers, 

I rerun the code for that image, and I got more or less what is originally printed in the book. I am using:

```
pandas==1.0.3
matplotlib==3.2.1
```

Which versions are you using? Maybe it's a compatibility problem? 
Also, thanks for the kind words about the book and for recommending it to your local library! It means a lot :)

**Comment by nickdesaulniers** [comment]
Oh, that's likely.  I'm getting a spew of deprecation warnings when I use Matplotlib in a jupyter notebook (and have to disable them).

Looks like I'm using python 3.6 and seeing a deprecation warning:
```
~/.local/lib/python3.6/site-packages/pandas/plotting/_matplotlib/converter.py:256: MatplotlibDeprecationWarning: 
The epoch2num function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  base = dates.epoch2num(dt.asi8 / 1.0e9)
```
I'm not sure how to check my version of matplotlib though.  Though maybe the warning is coming from pandas?  In `~/.local/lib/python3.6/site-packages/pandas/` there's a `_version.py` file that says version 1.0.5, so maybe it should be updated or reported upstream.

**Comment by erykml** [comment]
If possible, please try to update the libraries and run the code again. The test I did today was done on Python 3.7.3. Let me know if it works :)

**Comment by nickdesaulniers** [comment]
(Sorry, edited my comment above, working between two machines, please take a look)

**Comment by nickdesaulniers** [comment]
Unrelated; I've been interested in this example of GBM for calculating probability of touching or being ITM for a given strike. I'm curious @erykml if you have thoughts: For European exercise, I could likely compare the final observation of the walk. For American exercise, I suspect I'd have to check whether any point of a given walk crossed a given strike, since the option could have been exercised before expiration. I wonder with enough simulations whether those two are the same?

I've also seen ThinkOrSwim has a Probability of Expiration cone indicator. I've been having trouble finding precisely how they calculate it, but do you suppose it's just the max and min values of such a walk? Oh, I guess max and min wouldn't be 1 std dev of the values of the walk.

**Comment by erykml** [comment]
Hi @nickdesaulniers, sorry for the late reply, really busy times.

Regarding the version of the library, you can use the following code `pip freeze | grep matplotlib` to quickly inspect the version of the library. 

On the second matter, yes, you can use GBM simulations to determine the value of both European and American options as you have described. As a matter of fact, this is also covered in the book :) There, I also compared the prices of the options calculated using simulations vs. closed for solutions (provided they exist).

Regarding the Probability of Expiration (from what I saw here https://tlc.thinkorswim.com/center/reference/Tech-Indicators/studies-library/O-Q/ProbabilityOfExpiringCone), they use some undisclosed methods to simulate forecasted stock prices and calculate the mean and standard deviation for each time point to plot the cone. As you can see, the cone expands over time, as there is more and more uncertainty with each step. You can also try to calculate such a cone using the code from the book as the starting point :)

Hope this helps!

Cheers, 
Eryk
