### ISSUE TITLE
qf.iplot() is Blank in Colab

### ISSUE THREAD

**Issue by JeremyWhittaker** [PacktPublishing/Python-for-Finance-Cookbook#7]
I'm running 

`qf.iplot()`

from file "chapter_2.ipynb" and it's just displaying a blank window in Google Colab. Is there a fix for this?

**Comment by erykml** [comment]
Hi!

I have not tested all the code in Colab, maybe you could try the suggested solution from [here](https://stackoverflow.com/questions/52859983/interactive-matplotlib-figures-in-google-colab) with `configure_plotly_browser_state()`.
